---
language: ruby
sudo: false
cache: bundler
rvm:
  - "2.7"
notifications:
  email: false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
    secure: WAtIHHjBdoPXQNWZe5tZf7BJtM/cMcrxaH2zWrTyFiQ6EYg7FOnCmWCBVqcL6OGOT0/VkhFxAvVd5u+TlRw262hT0Rd+Eck70xnVJ0E7rii3i/2cld8uHeDamxt9OwuJKitmJyLjmfGBsFD0gGTNS0Y5ekBylbSEMVG4to6shSM=
